### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by naimbk** [Thibaut-Mouton/react-spring-messenger-project#1]
hello thibaut i need to integrate your code in my project but i find some problem

**Comment by Thibaut-Mouton** [comment]
Hello Naimbk,
What is your problem ?

**Comment by naimbk** [comment]
hello...i have login with email in my jwt i dont have username lik you so i
found some probleme especially in wstoken

**Comment by Thibaut-Mouton** [comment]
I don't fully understand your problem. 
When you register, you have to set an username and this is that field which will be used in the app header once you are connected.
Usernames in the Readme are juste for the example

**Comment by naimbk** [comment]
yes i khnow that,one last question you have wstoken saved in database that i dont understand how you generate him i don't find any methode that generate that

**Comment by Thibaut-Mouton** [comment]
The wsToken is created when your create your account into the application.

In the [`ApiController.java` ](https://github.com/Thibaut-Mouton/react-spring-messenger-project/blob/main/backend/src/main/java/com/mercure/controller/ApiController.java) file, the method `createUser(@RequestBody String data)` generate a wsToken (random uuid) and then store it in the database.

This token is used to authenticate the user for the websocket channel.

**Comment by naimbk** [comment]
Thank you so much

**Comment by Thibaut-Mouton** [comment]
You're welcome, do not hesitate if you have other questions.
