### ISSUE TITLE
Frontend app is not working on win 10.

### ISSUE THREAD

**Issue by cyberic-icus** [Thibaut-Mouton/react-spring-messenger-project#10]
I was running the project on Win 10. The backend and database are up and running, but I'm having trouble with the frontend. The linter is throwing errors, and after I removed the linter, the application freezes and throws strange errors. Could you please help me get the frontend running, at least within Docker? I would really appreciate your help :( 

![image](https://github.com/Thibaut-Mouton/react-spring-messenger-project/assets/58913963/c373fb63-b844-481e-8187-1d96676a6963)

**Comment by cyberic-icus** [comment]
```xml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="icon" href="/favicon.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="theme-color" content="#000000"/>
    <meta
            name="description"
            content="Web site created using create-react-app"
    />
    <link rel="apple-touch-icon" href="/logo192.png"/>
    <link rel="manifest" href="/manifest.json"/>
    <title>Fast Lite Message | FLM</title>
<script defer src="/static/js/bundle.js"></script></head>
<body>
<noscript>You need to enable JavaScript to run this app.</noscript>
<div id="root"></div>
</body>
</html>
```

**Comment by Thibaut-Mouton** [comment]
Hello, 
Can you confirm that you are on the `develop` branch ?
And can you provide your nodejs version ?
Thanks

**Comment by Thibaut-Mouton** [comment]
Hello, due to inactivity, I'm closing this issue. Feel free to re-open a new one if you still have issues.
